version: '3'

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=password
